# Generated by Django 5.2.14 on 2026-05-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='update_type',
            field=models.CharField(choices=[('5_over', '5 Over'), ('10_over', '10 Over'), ('key_moment', 'Key Moment')], db_index=True, default='key_moment', max_length=20),
        ),
    ]
