# Generated by Django 5.2.14 on 2026-05-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_team_one_score', models.CharField(blank=True, max_length=50, null=True)),
                ('last_team_two_score', models.CharField(blank=True, max_length=50, null=True)),
                ('last_over', models.CharField(blank=True, max_length=20, null=True)),
                ('last_event', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_state', to='matches.match')),
            ],
        ),
    ]
