# Generated by Django 5.2.14 on 2026-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchstate',
            name='last_event',
        ),
        migrations.AddField(
            model_name='matchstate',
            name='last_over_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='last_result_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='last_six_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='last_wicket_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
