# Generated by Django 5.2.14 on 2026-05-13 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one_score', models.CharField(blank=True, max_length=50, null=True)),
                ('team_two_score', models.CharField(blank=True, max_length=50, null=True)),
                ('current_over', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('COMPLETED', 'Completed')], default='LIVE', max_length=20)),
                ('match_time', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one_matches', to='matches.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two_matches', to='matches.team')),
            ],
        ),
    ]
